# Site wide configuration

title: "Your Awesome Site"
description: "A Coming Soon Template"
#if you modify locale please have a look at _data/messages.yml too
locale: fr
#for meta name="author" :
author: ygotame 

#Target date in UTC / GMT
countdown:
  theme: red
  year: 2020
  month: 1
  day: 11
  hour: 11
  minute: 11

# Site owner
owner:
  name:
  email: yamlal@gotame.com
  twitter:
  google-plus: yamugotame@gmail.com
  instagramm:
  #Aboutlink = German "Impressum", provide url and caption (eg "Impressum")
  aboutlink:
    url:
    caption:


# Jekyll configuration
sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: rouge


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
